on:
  schedule:
  # See https://crontab.guru/#0_0_1_*/1_*
    - cron: "0 0 1 */1 *"
  push:
     branches:
       - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - shell: bash
      run: |
        curl -X GET https://dl.google.com/android/studio/metadata/distributions.json -o data.json
        # git config --global user.name "GitHub Action"
        # git config --global user.email "test@gmail.com"
        # git add data.json
        # git commit -m "Fetched latest distribution data"
        # git push
